### ISSUE TITLE
Cucumber tests might not be triggered

### ISSUE THREAD

**Issue by DoxasticFox** [Australian-Genomics/CTRL#18]
There appear to be cucumber tests in the source code, [here](https://github.com/Australian-Genomics/CTRL/tree/e8967f79874459500b2887851cc96275d79af699/features/consent). But I'm not sure the rspec tests are running them. There is no documentation on how to run these either.

A satisfactory resolution to this issue would be to document how to run the cucumber tests in the readme and run them in CI, if they aren't already being run.

**Comment by DoxasticFox** [comment]
I've attempted to run the tests with this:

```
docker-compose run web bash -c 'RAILS_ENV=test bundle exec rake cucumber'
```

The tests fail because `chromedriver` isn't installed on the docker container. Example:

```
  Scenario: User can see the step two of the consent # features/consent/confirm_answers.feature:11              
    When I click on Register                         # features/step_definitions/user_steps.rb:85               
      Unable to find chromedriver. Please download the server from                                              
      https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.               
      More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.                                    
       (Selenium::WebDriver::Error::WebDriverError)     
      ./features/step_definitions/user_steps.rb:86:in `"I click on Register"'                                   
      ./features/support/database_cleaner.rb:11:in `block in <top (required)>'                                  
      features/consent/confirm_answers.feature:12:in `When I click on Register'                                 
    And I fill in the user details                   # features/step_definitions/user_steps.rb:89               
    Then I should see the step one of consent        # features/step_definitions/step_two_steps.rb:17           
    When I click on Next                             # features/step_definitions/step_one_steps.rb:1            
    Then I should see the step two of the consent    # features/step_definitions/step_two_steps.rb:23           
WARN: Screenshot could not be saved. `page.current_path` raised exception: #<Selenium::WebDriver::Error::WebDriverError: Unable to find chromedriver. Please download the server from
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.                     
More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```
